<?php
return [
   '/admin' => VIEW_PATH . '/admin/dashboard.php',
    '/admin/login' => VIEW_PATH . '/admin/login.php',
    '/admin/logout' => VIEW_PATH . '/admin/logout.php',
    '/admin/authenticate' => VIEW_PATH . '/admin/authenticate.php',
    '/admin/manage_admin' => VIEW_PATH . '/admin/manage_admin.php',
    '/admin/add_admin' => VIEW_PATH . '/admin/add_admin.php',
    '/admin/save_admin' => VIEW_PATH . '/admin/save_admin.php',
    "/admin/edit_admin" => VIEW_PATH . '/admin/edit_admin.php',
    "/admin/update_admin" => VIEW_PATH . '/admin/update_admin.php',
    '/admin/delete_admin' => VIEW_PATH . '/admin/delete_admin.php',
    '/admin/profile' => VIEW_PATH . '/admin/profile_admin.php',
    '/admin/update_profile' => VIEW_PATH . '/admin/update_profile.php',
    '/admin/change_password' => VIEW_PATH . '/admin/change_password.php',
    '/admin/edit_aspirasi' => VIEW_PATH . '/admin/edit_aspirasi.php',
    '/admin/update_aspirasi' => VIEW_PATH . '/admin/update_aspirasi.php',
    '/admin/delete_aspirasi' => VIEW_PATH . '/admin/delete_aspirasi.php',
    '/admin/review_aspirasi' => VIEW_PATH . '/admin/review_aspirasi.php',
    // Kelola Kategori (Fitur 3)
    '/admin/manage_kategori' => VIEW_PATH . '/admin/manage_kategori.php',
    '/admin/save_kategori'   => VIEW_PATH . '/admin/save_kategori.php',
    '/admin/edit_kategori'   => VIEW_PATH . '/admin/edit_kategori.php',
    '/admin/update_kategori' => VIEW_PATH . '/admin/update_kategori.php',
    '/admin/delete_kategori' => VIEW_PATH . '/admin/delete_kategori.php',
];
